events {
  worker_connections 1024;
}

stream {
  upstream my_server {
    least_conn;
    server server1:9090;
    server server2:9090;
    server server3:9090;
  }

  server {
    listen 9090;
    proxy_pass my_server;
    proxy_connect_timeout 10s;
    proxy_timeout 1m;
  }
}
